baseURL = "https://mauriciovegaenterprise-contacto-whatsapp.netlify.com"
languageCode = "es-co"
title = "Mauricio Vega Enterprise"
themesDir = "themes"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Mauricio Vega"

  [params.homepage_meta_tags]
    meta_description = "Mauricio Vega Enterprise: Tus trámites notariales en tiempo récord"
    meta_og_title = "Mauricio Vega Enterprise: Tus trámites notariales en tiempo récord"
    meta_og_type = "website"
    meta_og_url = "https://mauriciovegaenterprise-tramites-en-tiempo-record.netlify.com/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Te acompañamos para realizar tus trámites de notaría en menos tiempo, ahorrando dinero y sin necesidad de hacer filas. Tenemos cobertura permanente en Medellín y Bucaramanga."
    meta_twitter_card = "summary"
    meta_twitter_site = "@mventerprise"
    meta_twitter_creator = "@mventerprise"

[menu]
  # Main Menu

    [[menu.main]]
      name = "Facebook"
      url = "https://www.facebook.com/mauriciovegaenterprise/"
      weight = 1

    [[menu.main]]
      name = "Instagram"
      url = "https://www.instagram.com/mauriciovegaenterprise/"
      weight = 2

    [[menu.main]]
      name = "WhatsApp"
      url = "https://api.whatsapp.com/send?phone=573193880958&text=Deseo%20saber%20acerca%20de%20sus%20servicios"
      weight = 0

    [[menu.main]]
      name = "E-mail"
      url = "mailto:contacto@mauriciovegaenterprise.com"
      weight = 4


  # Footer Menu
    [[menu.footer]]
      name = "Facebook"
      url = "https://www.facebook.com/mauriciovegaenterprise/"
      weight = 1

    [[menu.footer]]
      name = "Instagram"
      url = "/contact/"
      weight = 2
